nvim-orgmode/orgmode

- README.md
Hi,
I am just want to give my good feeling about your handcraft.
Good job and thank you for your hard work. 👍
> Add escape char for <CR> on README.md

- .github/workflows/tests.yml
- tests/plenary/object/date_spec.lua
> Fix date test timestamp assert.

- DOCS.md
- lua/orgmode/agenda/init.lua
- lua/orgmode/config/defaults.lua
The new configuration will set the min height for the agenda
> Added a new configuration org_agenda_min_height

- DOCS.md
- lua/orgmode/capture/templates.lua
- tests/plenary/capture/templates_spec.lua
Adds support for the following template expansions:
- username
- clipboard
- calling file
- prompts
- expressions
> Enhance template expansion

- ftdetect/filetype.lua
As discussed on https://www.reddit.com/r/neovim/comments/rvwsl3/introducing_filetypelua_and_a_call_for_help/ .
> Add filetypes.lua file for the package.

- ftdetect/filetype.lua
> Check if vim.filetype is defined before calling functions

- lua/orgmode/capture/init.lua
#196 
Haven't written a test yet but would appreciate feed back on whether it looks like a good implementation, thanks
> Add refile_to_headline

- lua/orgmode/capture/init.lua
- tests/plenary/capture/capture_spec.lua
This adds the orgmode functionality documented
here: https://orgmode.org/manual/Template-elements.html
> #248 Add multi-key capture shortcut support

- lua/orgmode/org/mappings.lua
- lua/orgmode/treesitter/headline.lua
- lua/orgmode/utils/treesitter.lua
This PR is based on this discussion issue #271
> Use treesitter for buffer actions

- lua/orgmode/capture/init.lua
- lua/orgmode/org/hyperlinks.lua
- lua/orgmode/parser/file.lua
- lua/orgmode/parser/files.lua
- tests/plenary/ui/mappings_spec.lua
> Check for 'end of string' when searching headline

- DOCS.md
Improved readability, especially in `Highlight Groups` and `org_capture_templates` subsubsection.
> Improve readability on DOCS.md

- lua/orgmode/treesitter/headline.lua
- tests/plenary/object/todo_state_spec.lua
> Handle multiple substitutions in custom todo keyword

- lua/orgmode/config/init.lua
fixes #318
@kristijanhusak I'm giving up on giving those variables a meaningful name. `map` contains the rhs + opts, any idea what it should be called?
> Add handling of multi-key mappings

- lua/orgmode/objects/help.lua
I think this way the function is more consistent with the rest of the project.
@kristijanhusak I hope you don't mind
> Make Help:show() more explicit

- lua/orgmode/objects/help.lua
> Fix typo in help overlay

- DOCS.md
- lua/orgmode/agenda/init.lua
- lua/orgmode/config/defaults.lua
- lua/orgmode/config/mappings/init.lua
closes #339
Needs some more testing. Looks to me like it may archive more than intended
> Enable archiving from agenda

- lua/orgmode/org/indent.lua
- queries/org/org_indent.scm
> allow block folding

- lua/orgmode/capture/init.lua
fixes [the bug](https://github.com/nvim-orgmode/orgmode/discussions/311#discussioncomment-2839909) mentioned in #311
- refiling to a correct org-file with an incorrect headline resulted in an error, due to the function `_refile_to_end` being called with `.` instead of `:`
- display an error message when trying to refile to a file that is not part of the files set in `org_agenda_files`
- display an error message when trying to refile to a headline that is non-existent in the destination file
> Fix wrong function access & output refile error

- lua/orgmode/org/mappings.lua
- tests/plenary/fixtures/todo.org
- tests/plenary/ui/mappings_spec.lua
fixes #403
This was eerily simple, I probably overlooked something. 
I just changed some tests, so I wouldn't have to add some dedicated ones. Let me know if that's a nono
also: 
- fixed a typo
- lots of formatting changes. Let's see if the CI agrees with my stylua
> Allow asterisk bullets for plain lists

- lua/orgmode/org/mappings.lua
Addresses [this](https://github.com/nvim-orgmode/orgmode/issues/366#issuecomment-1236820452)
> Look for link before looking for date

- queries/org/highlights.scm
> Add whole tag_list to highlightgroup

- lua/orgmode/config/init.lua
- lua/orgmode/objects/priority_state.lua
- tests/plenary/object/priority_state_spec.lua
fixes #382 
@kristijanhusak I'd like to hear your opinion on the validation of priorities provided by the users config. It's a bit messy I think.
> Fix broken priority cycling

- lua/orgmode/objects/calendar.lua
did some cleanup of the code while I was at it
> Calendar next/prev supports count prefix

- README.md
Apparently I forgot to add it, my bad
> Add link to matrix chat

- lua/orgmode/agenda/init.lua
- lua/orgmode/agenda/views/agenda.lua
- lua/orgmode/agenda/views/search.lua
- lua/orgmode/agenda/views/tags.lua
- lua/orgmode/agenda/views/todos.lua
- lua/orgmode/utils/init.lua
> Fix wrong tag offset in agenda

- DOCS.md
- doc/orgmode.txt
removes the duplicate tag `org_capture_show_help`
> fix note docs

- lua/orgmode/agenda/init.lua
- lua/orgmode/objects/help.lua
closes #445 
I chose to just use `vim.b.org_agenda_type` after all, as it was easier than passing it through with `opts`. If it is obfuscating the logic too much, let me know
> Agenda help improvements

- lua/orgmode/parser/logbook.lua
- lua/orgmode/parser/section.lua
Updates type annotations in `Logbook` and `Section`
Adds and updates type annotations to reflect the actual implementations of the
modules/classes.
> Improves type annotations

- DOCS.md
- lua/orgmode/config/defaults.lua
- lua/orgmode/org/mappings.lua
- lua/orgmode/treesitter/headline.lua
- tests/plenary/ui/mappings/todo_spec.lua
> Add org-log-into-drawer

- lua/orgmode/objects/calendar.lua
Make `OrgCalendarToday` customizable.
> fix(calendar): make highlight overrideable

- lua/orgmode/capture/init.lua
- use correct line position from target headline
- reset cursor back
- fix issue #633
> fix: repair refile to headline in the same file (#633)

- .github/workflows/tests.yml
- tests/minimal_init.lua
Fix issues with nightly tests by using custom clipboard implementation.
> ci: Fix nightly tests

- README.md
"Clocking time" has been appearing twice in the Features list
> Remove duplicate list item

- DOCS.md
- lua/orgmode/babel/init.lua
- lua/orgmode/babel/tangle.lua
- lua/orgmode/config/defaults.lua
- lua/orgmode/config/init.lua
- lua/orgmode/config/mappings/init.lua
- lua/orgmode/files/elements/block.lua
- lua/orgmode/files/file.lua
- lua/orgmode/files/headline.lua
- lua/orgmode/org/mappings.lua
- lua/orgmode/ui/virtual_indent.lua
- lua/orgmode/utils/init.lua
- lua/orgmode/utils/treesitter.lua
- tests/plenary/babel/tangle_spec.lua
- tests/plenary/capture/capture_spec.lua
- tests/plenary/files/file_spec.lua
- tests/plenary/files/headline_spec.lua
- tests/plenary/helpers.lua
Partially adresses these:
* https://github.com/nvim-orgmode/orgmode/issues/485
* https://github.com/nvim-orgmode/orgmode/issues/190
* https://github.com/nvim-orgmode/orgmode/issues/377
> feat(babel): Add support for org tangle and basic noweb

- DOCS.md
- lua/orgmode/agenda/agenda_item.lua
- lua/orgmode/agenda/views/agenda.lua
- lua/orgmode/agenda/views/todos.lua
- lua/orgmode/colors/highlights.lua
- lua/orgmode/colors/init.lua
- lua/orgmode/config/init.lua
- lua/orgmode/files/headline.lua
- queries/org/highlights.scm
Closes https://github.com/nvim-orgmode/orgmode/pull/598
> feat(highlights): Add highlights for priorities

- .github/workflows/luarocks.yml
Depends on https://github.com/nvim-orgmode/tree-sitter-org/pull/1
> feat: rocks.nvim/luarocks support

- DOCS.md
- lua/orgmode/agenda/init.lua
- lua/orgmode/api/headline.lua
- lua/orgmode/capture/template/init.lua
- lua/orgmode/objects/calendar.lua
- lua/orgmode/objects/date.lua
- lua/orgmode/org/mappings.lua
> feat(capture): Add date prompt expansions

- .github/workflows/luarocks.yml
luarocks-build-treesitter-parser now needs tree-sitter-cli.
Sorry, I completely forgot about this :sweat_smile: 
Closes #786
> ci(luarocks): fix luarocks upload

- docs/plugins.org
This PR adds [rolodex.nvim](https://github.com/michhernand/rolodex.nvim) to the list of plugins for Orgmode.
rolodex.nvim provides:
1. Autocomplete for teammates / contacts into Orgmode (and other) files.
2. A local plaintext contacts file.
3. Ability to add new names to contacts file from Neovim.
`make test`.
> feat/add plugin rolodex.nvim

- .github/workflows/tests.yml
- Makefile
- docs/contributing.org
- lua/orgmode/utils/treesitter/install.lua
- tests/plenary/capture/capture_spec.lua
- tests/test.lua
Run tests on multiple operating systems
> ci(tests): run tests on multiple OS
