nvim-orgmode/orgmode

DOCS.md
doc/orgmode.txt

The documentation is missing a reference to the target option for a capture template. I was trying to implement it myself but found it was already there. Also fixed a missing newline in the variables list.

Add example for capture templates

---

DOCS.md
doc/orgmode.txt
lua/orgmode/capture/templates.lua
lua/orgmode/org/mappings.lua

In addition to file link, emacs org mode uses the line number in the template. I decided to add it to this org-mode and add the functionality needed to jump to the line number when editing the file.

Add file line number hyperlink

---

lua/orgmode/objects/calendar.lua

Currently users are able to modify the calendar buffer, this can lead to situations where they might accidentally delete parts of the calendar and leave it unusable. Emacs' org mode calendar works a bit differently but it is not editable either. Setting the calendar buffer as not modifiable after rendering it solves the issue.

Set calendar buffer as nonmodifiable

---

indent/org.vim
lua/orgmode/org/indent.lua

This commit adds a better ```foldtext``` function that replaces leading stars with spaces when ```org_hide_leading_stars``` is true.
Example without this commit (Lines 2 and 5 are folded):
Same example with this commit:
Thanks

Folded text respects org_hide_leading_stars

---

syntax/org.vim

This causes a lot of weird behaviour, especially when
`org_hide_emphasis_markers` is true.
To fix it, change the `org_bold` syntax to not allow bold statements that start with two `*`.

headline with four * trigger bold syntax

---

lua/orgmode/org/mappings.lua
tests/plenary/ui/mappings_spec.lua

I forgot to rename this here after I renamed it in tree-sitter-org
Bonus fix, enter in listitems if the cursor is between the bullet and the item
I wrote test cases for both of them.

bug: rename `itemtag` to `description`

---

ftplugin/org.vim
lua/orgmode/org/indent.lua

This is just a simple change to make folded headlines look cleaner and more like Emacs's folds

Clean up foldtext

---

lua/orgmode/org/indent.lua

This minor change removes the extra `*` in a folded `:PROPERTIES:` drawer
Before
After

Remove excess `*` in drawer fold text

---

Makefile
lua/orgmode/org/autocompletion/omni.lua
lua/orgmode/org/hyperlinks.lua
lua/orgmode/org/mappings.lua
tests/plenary/org/autocompletion_spec.lua

As a summary:
- Complete org files on 'file:'
https://user-images.githubusercontent.com/31262046/138616359-e4f256f7-af76-4983-b5a1-945f5e56542b.mp4
- Complete headers based on current 'file:' context
https://user-images.githubusercontent.com/31262046/138616389-346f8e01-4d5f-4826-b19c-db7a850834c9.mp4
- Support jumping to specific section in file from hyperlink
https://user-images.githubusercontent.com/31262046/138616420-61c4f986-d2ab-4d07-9a0b-002f05058fa3.mp4
---
For original _Emacs_ functionality, see [here](https://orgmode.org/manual/External-Links.html). I still have some things to review myself and clean up before I would consider this "non-WIP", but the main functionality is there.

Enhance file: link support

---

DOCS.md
doc/orgmode.txt
lua/orgmode/notifications/init.lua

Two changes:
1. Add note in doc. about `conceallevel` being required to hide emphasis markers, "fixes" #124
2. Fix default checks for 0/1 instead of Lua-style boolean for `vim.fn.executable` (used with notifications in this case, but checked elsewhere and other places look good from what I can tell too)

Docs update and notification fix

---

DOCS.md
doc/orgmode.txt

docs: Fix duplicate tag when generating :helptags

---

DOCS.md
doc/orgmode.txt
lua/orgmode/config/defaults.lua
lua/orgmode/org/indent.lua

I should have made this configurable from the start but now users can configure what to replace fold markers with. This replicates the `org-ellipsis` setting [available on Emacs](https://emacs.stackexchange.com/a/10986).
Also partially addresses #134

feat: add org-ellipsis

---

DOCS.md
doc/orgmode.txt
lua/orgmode/colors/highlights.lua
queries/org/highlights.scm

Overview:
- Name highlights in Treesitter query file and link them defaults to allow overriding
- Start documentation for highlight groups
- Include "TS" in Treesitter highlights to make it more apparent which are which
with some remaining tasks:
Probably don't need _all_ of the highlight groups present to start, but posting this as a _mostly finished_ draft to get your opinions @kristijanhusak. Any objections to linking things like `org_code` to `OrgCode` highlight groups and similar to follow a similar naming scheme?

Treesitter highlight documentation and default linking

---

lua/orgmode/config/init.lua

Hello! thank you for this amazing plugin. 
I've encountered one issue while using thils.
The manual says it supports multiple key mappings, so I tried this
```lua
global = {
org_agenda = {'gA', '<C-c>a'},
org_capture = 'gC'
},
```
However, this gives following error message:
This PR is an attempt to fix this. Thanks!

fix: allow multiple key mappings to global

---

lua/orgmode/org/indent.lua

I'm not sure what changed, but hiding leading stars on folded lines stopped working for me. This commit escapes the regex string more explicitly and seems to fix the issue.

fix org_hide_leading_stars on folded lines

---

DOCS.md
doc/orgmode.txt
lua/orgmode/colors/highlights.lua
lua/orgmode/config/defaults.lua
lua/orgmode/config/mappings.lua
lua/orgmode/objects/edit_special/init.lua
lua/orgmode/objects/edit_special/types/src.lua
lua/orgmode/objects/edit_special/utils.lua
lua/orgmode/objects/help.lua
lua/orgmode/org/mappings.lua
lua/orgmode/parser/file.lua
lua/orgmode/utils/init.lua
tests/plenary/ui/edit_special_src_spec.lua

This resolves #146.
Right now there's a lot going on in a function that is really only supposed to be handling the mapping, so if you'd rather have this put somewhere else let me know.
The first iteration used an `acwrite` buffer which ends up being a bit cleaner as we aren't creating unecessary files, but most language servers (or at least things in `nvim-lspconfig`) expect a file on disk (e.g. such that a root directory can be found). From this then, I've just gone with `:h tempname()` which solves those problems and is mostly no different.
For now the default is using a simple split as a floating window has some issues with the completion menu (it ends up covering the current cursor position) and I imagine the main use case here is for language servers or similar.
Quick demo: …

feat: Edit source blocks in a buffer with the associated filetype

---

DOCS.md
doc/orgmode.txt
lua/orgmode/config/defaults.lua
lua/orgmode/export/init.lua

emacs html export requires the htmlize package which is no longer included in the latest orgmode for emacs (I'm using emacs 26.3). If you export to html -> emacs with a code block it breaks since it uses htmlize to syntax highlight. (btw, get the same error in emacs when trying to export)
That being said, when I install the htmlize package in emacs, exporting from emacs works, but still fails from orgmode.nvim. The reason is because the `--batch` flag doesn't source your emacs configuration and any packages you have. This PR adds a `--load` switch to the export command that points at your emacs config. This tells emacs running in batch mode to load a specific startup file, in this case the main emacs config.
> **NOTE** Changes beyond this. We may want to have a config option for …

Bug Fix: emacs html export

---

DOCS.md
README.md
lua/orgmode/config/defaults.lua
lua/orgmode/config/mappings.lua
lua/orgmode/org/mappings.lua
tests/plenary/ui/mappings_spec.lua

Toggle headlines

---

DOCS.md

Several config examples use the non-existing `org_agenda_file` variable, which I replace by the correct `org_agenda_files`

[doc] Replace org_agenda_file by org_agenda_files

---

lua/orgmode/objects/calendar.lua

This PR makes the default cursor movements "magnetic", so that they stick onto the days. I think this behavior is much more intuitive than leaving `hjkl` to be the same as it is for plain text.
Demo:
[![asciicast](https://asciinema.org/a/ErRBNen2uEIBb37I2l2oEgG0T.svg)](https://asciinema.org/a/ErRBNen2uEIBb37I2l2oEgG0T)

Restrict cursor movement in calendar

---

lua/orgmode/colors/todo_highlighter.lua

Fix for #234 by gathering all highlight queries then calling vim.treesitter.set_query().

fix custom highlight queries

---

lua/orgmode/agenda/views/agenda.lua

Moved priority sorting in the `sort_by_date_or_category` function so it gets done for same day items as well. Renamed func to `sort_by_date_or_priority_or_category`, a bit wordy but more adequate :slightly_smiling_face: 
Before:
After:
<details>
<summary>Contents of test2.org</summary>
```org
* TODO [#A] Task 1
SCHEDULED: <2022-03-27 нед>
* TODO [#B] Task 2
SCHEDULED: <2022-03-27 нед>
* TODO [#C] Task 3
SCHEDULED: <2022-03-27 нед>
* TODO [#A] Task 4
SCHEDULED: <2022-03-27 нед>
* TODO [#B] Task 5
SCHEDULED: <2022-03-27 нед>
* TODO [#C] Task 6
SCHEDULED: <2022-03-27 нед>
```
</details>

Priority sort for same day items

---

ftdetect/filetype.lua
ftdetect/org.vim
ftdetect/org_archive.vim

Neovim 0.7 can detect org filetypes by [default](https://github.com/neovim/neovim/pull/17939). Once 0.7 is officially released, the ftdetect directory in the plugin is redundant

Prepare for 0.7 release to use default ftplugin

---

lua/orgmode/agenda/init.lua

When jumping to a headline from the agenda with `<CR>` or `<Tab>` and if the file
is folded, just setting the cursor doesn't reveal the folds.
By calling `zv` after positioning the cursor we reveal up to the cursor

Reveal headline when jumping from agenda

---

lua/orgmode/agenda/init.lua
lua/orgmode/capture/init.lua
lua/orgmode/export/init.lua
lua/orgmode/utils/init.lua

The separator char for the capture prompt in Emacs appears to be `=` ([here](https://youtu.be/qCdScs4YO8k?t=98)) but I think we can get by making them all `-` instead. As every menu should use a separator after the title, we can also get rid of some magic numbers.

Make menu prompts more uniformly

---

lua/orgmode/objects/edit_special/init.lua
lua/orgmode/org/autocompletion/omni.lua
lua/orgmode/org/syntax.lua
lua/orgmode/parser/file.lua
syntax/org.vim
syntax/org_legacy.vim
tests/plenary/org/autocompletion_spec.lua

Closes #86 by adding the lowercase `begin_src/end_src` to the syntax match group for language highlighting

Fix lowercase src highlighting

---

lua/orgmode/parser/section.lua

fixes #246 
Turns out hyphens are special in Lua 'regex' patterns: [stackoverflow](https://stackoverflow.com/a/29379912/5356183)
And a hyphen is not the only special character. I suggest we also add a pattern-validation function to `orgmode.utils` like suggested in the answer.

Fix todo-keywords containing hyphens in agenda views

---

lua/orgmode/config/init.lua

This PR adds support for mappings in other modes than normal-mode, as discussed in #249 .
@kristijanhusak fyi I'm still working on the part concerning your `vim.keymap.set` example ;)

Enable mappings for different modes

---

lua/orgmode/agenda/views/agenda.lua

For some reason time stamp based sorting was failing (some merge broke it?):
I've fixed this adding a precedence sort if both items are on the same day and have a time stamp.

Fixed time stamp based sorting

---

lua/orgmode/capture/init.lua
lua/orgmode/config/init.lua

This fixes an issue where you would end up with two references to the default file when using symlinks, since all other files had their symlinks resolved but not this.
This led to having one reference to the full path of the file, and one reference to the symlink, giving symptoms such as duplicate entries in the agenda.
This fix is very similar to [this](https://github.com/nvim-orgmode/orgmode/commit/60a101616bbf9b0dec11e44a46e8395509fc373e) one.

Resolve path for `default_notes_file` to support symlinks.

---

ftplugin/org.vim

currently the plugin will override the user's `fillchars` when setting `fold:c`, this unintentionally set's everything else beck to their defaults (such as `horiz:c` or `vert:c` for example)

Fix overriding of global fillchars

---

DOCS.md

btw, is [this](https://github.com/nvim-orgmode/orgmode/blob/72a7a62530e110bd999e9b55d23308d7dbeb39a4/DOCS.md?plain=1#L124) a typo? It's the same as the mode above it

Add Hyperlink section to docs

---

lua/orgmode/config/defaults.lua
lua/orgmode/treesitter/headline.lua
tests/plenary/ui/mappings_spec.lua

The `tags_width` was being subtracted in any case, which resulted in flushright alignment per default. When a negative `tag_column` value was given, the `tags_width` was subtracted twice, resulting in a broken alignment.

Fix wrong tag_column indentation

---

lua/orgmode/capture/templates.lua

When capturing an item with cursor placeholder `%?` the placeholder
itself is getting yanked.

fix(capture): Do not yank cursor placeholder

---

lua/orgmode/events/init.lua
lua/orgmode/events/listeners/align_tags.lua
lua/orgmode/events/listeners/init.lua
lua/orgmode/events/types/headline_demoted_event.lua
lua/orgmode/events/types/headline_promoted_event.lua
lua/orgmode/events/types/init.lua
lua/orgmode/events/types/todo_changed_event.lua
lua/orgmode/init.lua
lua/orgmode/org/mappings.lua
tests/plenary/ui/mappings_spec.lua

@jgollenz this is the result of https://github.com/nvim-orgmode/orgmode/pull/410/files. I thought about it a little bit, and figured out we might need to do more things when something changes, not only this one. That's why I introduced an event dispatcher and few events that are fired, and tags are aligned through them.
This will also allow us to expose listener through the api, and allow people to hook into it if they want to do something.
Let me know what you think.

Add event dispatcher

---

lua/orgmode/export/init.lua

Hi! Thank you for this awesome plugin!
I found that the interface of default exporters is not very flexible, so I decided to improve it
- It's easy to add a new exporter. For example, I added the `pandoc` exporter for markdown:
```lua
submenu('m', 'Export to Markdown file', 'md', {
emacs = {
command = 'org-md-export-to-markdown'
},
pandoc = {
format = "gfm"
}
}),
```
- The labels of the exporters is generated automatically. For example, `My awesome exporter` becomes `My awesome exporter (emacs/pandoc)`:
```lua
submenu('d', 'My awesome exporter', 'docx', {
emacs = {
-- ...
},
pandoc = {
-- ...
}
}),
```
- The arguments for the exporters were separated

refactor(export): flexible exporters generation

---

lua/orgmode/colors/highlights.lua

fixes #416 
On 0.7.2 this will return 0, which is truthy in Lua. Thanks to @seandewar for pointing that out

Fix invalid `vim.fn.has('nvim-0.8')` check

---

lua/orgmode/capture/templates.lua

It says [here](https://orgmode.org/manual/Template-expansion.html) that `[the expansion of lisp expressions] happens after expanding non-interactive “%-escapes”, those can be used to fill the expression`. Fine, but this messes with Lua expressions, since its escape sequences overlap with those of orgmode templates. 
So, I guess we could do some aliasing for either one of the two sets, when they are within a `%(...)` Lua expression: 
- `%(return string.format("Hello, %s", @x)` aliasing template escapes
- `%(return string.format("Hello, @s", %x)` aliasing lua escapes
The `@` is just for demonstrative purposes, we could use else entirely.
This is the use case that actually prompted me to investigate that: `template = "* TODO [[%x][%(return string.match('%x', '([^/]+)$'))]]"`. I use it when I …

Enable expansions within lua expression

---

lua/orgmode/agenda/init.lua
lua/orgmode/agenda/views/agenda.lua

It says [here](https://orgmode.org/manual/Agenda-Commands.html): `Go forward in time to display the span following the current one. [...] With a prefix argument, repeat that many times.`

Advance agenda span with count

---

README.md

I'll open this so we can discuss how we could improve the current state of the README. Things I'd like to push for are: 
- Conciseness
- Showing > Describing
- Consistency
Changes I made so far ([have a look](https://github.com/jgollenz/orgmode/tree/refactor/readme)):
- Improved consistency for the code snippets
- Elevated some headlines so the structure closer resembles the top-level links
- Added 'Requirements' section
- Put 'Requirements', 'Installation', 'Setup' and 'Usage' under a 'Quickstart' section
- Renamed 'Gifs' to 'Showcase'
- Made the logo smaller
- Put the package managers and completion plugins into collapsible sections
Changes I propose:

README refactor

---

DOCS.md
doc/orgmode.txt
ftplugin/org.vim

Adds two additional abbreviations that allow users to easily insert the
current date or time as an inactive timestamp.

Adds :itoday: and :inow: abbreviations

---

README.md

I'm getting too used to the orgmode link syntax apparently

Fix wrong link syntax

---

lua/orgmode/colors/todo_highlighter.lua
lua/orgmode/utils/treesitter.lua

Calling `filetype detect` after setting the treesitter TODO highlights was triggering 2 back to back File.reload calls, since setting the `filetype` triggers the FileType autocommand.
Since we check if the filetype is already set, that means We can get away with just restarting the treesitter highlighter after adding new queries
This results in a noticeable perf improvement for me on when opening of an org file.

Don't reload orgfile twice

---

lua/orgmode/parser/search.lua
tests/plenary/parser/search_spec.lua

I noticed that in order to search agenda headlines using properties, the property names had to be all lower case. In Emacs, the property names are case insensitive when searching agenda items. I made a simple change to bring the behavior of nvim-orgmode in line with emacs.

Makes the property searching case insensitive

---

.editorconfig

I've created a basic `.editorconfig` file to reflect the current indentation settings of the repository. The repository's settings differed from the ones I had set by default so I added the config to respect the existing code style.
More information on editorconfig can be found [here](https://editorconfig.org/)

Adds editorconfig to maintain indentation

---

lua/orgmode/colors/custom_highlighter.lua
lua/orgmode/colors/hide_leading_stars.lua
lua/orgmode/colors/markup_highlighter.lua

This PR fixes flickers and slow scrolling issues by caching the queries by changetick.

Cache markup tree-sitter queries by changetick to improve performance

---

lua/orgmode/objects/date.lua
tests/plenary/object/date_spec.lua

Updates the repeater logic so that tasks which are completed before
their deadline has been reached, will properly repeat forward.

Fixes a bug in completing future tasks

---

tests/minimal_init.vim

My system's locale isn't en_US and therefore I had test failures on doing `make test`.

tests/minimial_init.vim: set language such that tests pass on non en_US systems

---

lua/orgmode/parser/file.lua

Allows a user to match using the implicit `CATEGORY` property as mentioned in org's
documentation [here](https://orgmode.org/manual/Categories.html)

Match by category

---

ftplugin/org.vim
lua/orgmode/utils/treesitter.lua
queries/org/folds.scm

Ok so
This is a truly amazing plugin
However, folding really works like shit for some reason. It always breaks. Here's a simple example:
I know it can collapse properties and other neat stuff. However, I personally don't need it. For me, it now collapses sections just perfectly, and I keep my sanity.

Use Treesitter for folding

---

DOCS.md
lua/orgmode/agenda/init.lua
lua/orgmode/capture/closing_note.lua
lua/orgmode/capture/init.lua
lua/orgmode/config/defaults.lua
lua/orgmode/notifications/init.lua
lua/orgmode/notifications/notification_popup.lua
lua/orgmode/objects/calendar.lua
lua/orgmode/objects/help.lua
lua/orgmode/utils/init.lua

closes #507 
@akinsho could you please have a look at this. It adds a new config option `win_border` that just passes the border options that can be passed to `nvim_open_win()` through.

Add 'win_border' config option

---

lua/orgmode/objects/date.lua
lua/orgmode/parser/file.lua
lua/orgmode/parser/search.lua
lua/orgmode/parser/section.lua
tests/plenary/parser/parser_spec.lua
tests/plenary/parser/search_spec.lua

An initial implementation of searching for headlines using date properties. This
PR requried a rewrite of the `Search` type to use a more traditional parsing
strategy internally. This allows for parsing more complicated queries more
easily, and also potential performance improvements since the query string is
parsed one time instead of every time the query is tested against a headline.

Date Searching

---

tests/minimal_init.vim

Having shada enabled sometimes breaks when running the tests from within a neovim session. Also, shada would get clobbered with synthetic test files. Therefore, disable it during testing.

No shada during tests

---

lua/orgmode/objects/calendar.lua

This patch removes the input lag when the `<` or `>` key is pressed.
https://user-images.githubusercontent.com/57654917/228636125-b7a70556-da2d-4297-a64f-0d924100af7f.mov
https://user-images.githubusercontent.com/57654917/228636148-145de163-562b-4ae4-a3d6-91d46d4ccf2f.mov

fix(calendar): remove key waiting

---

lua/orgmode/colors/markup_highlighter.lua
lua/orgmode/colors/todo_highlighter.lua
lua/orgmode/org/indent.lua
lua/orgmode/org/mappings.lua
lua/orgmode/treesitter/compat.lua
lua/orgmode/treesitter/headline.lua
lua/orgmode/treesitter/listitem.lua
lua/orgmode/treesitter/table.lua
lua/orgmode/utils/init.lua
lua/orgmode/utils/treesitter.lua

See neovim/neovim#22761 (maybe we should wait for the 0.9 release)

fix: update treesitter functions

---

lua/orgmode/objects/calendar.lua

This patch adds the ability to enter the date manually. It's a bit like how it's done in [emacs orgmode](https://orgmode.org/manual/The-date_002ftime-prompt.html):
https://user-images.githubusercontent.com/57654917/228889210-439302ad-fa5c-4772-9f0d-7c25b74c3aee.mov

feat(calendar): date jump

---

lua/orgmode/agenda/init.lua

I've been having the same issue as described in #490 for a while and finally had a chance to see if I could figure out the cause of it.
The view update fails every time I change the status of a todo item from AgendaTodosView. From what I can tell it seems to be caused by `win_width` not being set when calling `AgendaTodosView.generate_todo_item` from `Agenda:_remote_edit`, which leads to all sorts of weirdness in the TodosView when this call fails.

Fix promisify error in AgendaTodosView when changing todo state

---

lua/orgmode/org/mappings.lua

Classically, keymaps map one string of characters to another. Neovim also allows users to install a Lua function as a callback, like this:
```lua
vim.api.nvim_set_keymap('n', 'asdf', '', {callback = function()...end})
vim.keymap.set('n', 'asdf', function()...end, {})
```
In these cases, `vim.fn.maparg()` in dict-mode returns a table that does *not* contain a key `'rhs'`, but instead a key `'callback'` that points to this function. This is not documented; this bug is being tracked at <https://github.com/neovim/neovim/issues/22399>.
The function `OrgMappings.org_return()` was not prepared to handle this case. It would not call the callback function, and with `rhs==nil`, it would not even insert a line break. To the user, it appears as if the return key stopped doing anything in insert mode. …

Handle org_return correctly in face of Lua keymaps

---

lua/orgmode/org/mappings.lua

Without the check, attempting to open a link like `[[file:./file.org::*Heading]]` outside of any heading would cause a Lua error.
I'm not super proficient in Lua dev, so if there's any unit test I should add for this, I'd need some guidance.
In any case, thank you for working on this great plugin! :slightly_smiling_face:

fix: missing nil check in open_at_point()

---

lua/orgmode/colors/markup_highlighter.lua

This passes the `spell` option to `nvim_buf_set_extmark()` for all markup groups. In most cases, the passed value is simply `nil`, i.e. the same as if it were not passed at all.
In the following cases, however, we pass `spell=false`, i.e. forcefully disable spell-checking:
- the URL part of `[[URL][hyperlinks]]`;
- the inside of `[[hyperlinks]]` without description;
- `~code~` and `=verbatim=` spans;
- in-line LaTeX markup using `\(parentheses\)`.
The reason in all cases is that these spans are extremely likely to contain purposefully non-orthographic spelling, in particular hyperlinks.

Force-disable spellcheck in certain markup groups.

---

lua/orgmode/config/init.lua
lua/orgmode/utils/init.lua

I played around a bit with the problem described in #553. It seems to me that the point is that we are calling the wrong `old_cr_mapping`. I replaced `vim.fn.maparg` with `vim.api.nvim_get_keymap` and the problem went away.

fix(mappings): properly get old mapping

---

ftplugin/org.vim
indent/org.vim

Use `did_ftplugin` for early return is a standard practice in vim. The commit that introduced this change was aiming to solve a treesitter bug which should be outside of orgmode's scope (see #447).
At the time #447 was issued, I was thinking about this is a telescope bug, but indeed this is a treesitter's bug, see https://github.com/nvim-treesitter/nvim-treesitter/issues/4754.
And indeed this commit only solves #447 partially. The first time you opened an org file via telescope, the fold works correctly, but the second time you opened a file via telescope, the fold does not work again.
Based on above description, I think we should revert the changes and follow the standard practice of vim's ftplugin. And let the bugs to be fixed in upstream.

Revert "Remove checks for loaded ftplugin and indent"

---

lua/orgmode/org/hyperlinks.lua

Added a small check for hyperlinks that start with tildes to substitute them with `$HOME` on `<Leader>oo`.

Open file hyperlinks starting with ~

---

lua/orgmode/utils/init.lua

The previous implementation of `utils.open` did not properly check if the necessary executables were present. In Lua, `0` is treated as `true`, so it always tried to run `xdg-open` even when the executable was not found, preventing the proper command from being executed. This pr updates the check to correctly use the return values of `vim.fn.executable` and `vim.fn.has` functions.

fix: Fix executable check in `utils.open`

---

DOCS.md
lua/orgmode/config/defaults.lua
lua/orgmode/config/mappings/init.lua
lua/orgmode/org/mappings.lua

Described [here](https://orgmode.org/manual/Handling-Links.html#index-C_002dc-C_002dl)
There is no completion support for protocols (`http`, etc.) yet.
In light of other GH issues that are concerned with hyperlinks I'd like to discuss whether it makes sense to add a hyperlink object. It would possibly ease development in the future. Also, how about parsing them? Opening hyperlinks from the agenda requires to display all the links of a headline body to the user. There is also [`org-[next|previous]-link`](https://orgmode.org/manual/Handling-Links.html#index-C_002dc-C_002dl), that jumps to the next|previous link in the buffer

Add basic `org-insert-link` functionality

---

lua/orgmode/org/hyperlinks.lua
tests/plenary/org/autocompletion_spec.lua

Fixed headline autocompletion and jumping to files in parent or sibling directories. See also [org-open-at-point](https://orgmode.org/org.html#index-C_002dc-C_002do) in the Org manual. It solves issue [#583](https://github.com/nvim-orgmode/orgmode/issues/583).

fix: links with relative path to parent directories

---

lua/orgmode/org/mappings.lua

Currently pressing `6<C-A>` outside of a date just adds 1 instead of 6 to a number that isn't a date. This is because the fallback mapping does not include `vim.v.count1`.

`vim.v.count1` is needed on fallback mapping so `<count><C-A>` mappings work outside dates

---

DOCS.md
lua/orgmode/capture/init.lua
lua/orgmode/capture/templates.lua

Internally this compiles the target of the capture template the same way the template itself is compiled.
Also update the docs accordingly.
This is inspired by: https://github.com/nvim-orgmode/orgmode/discussions/540

Allow dynamic target in capture templates

---

DOCS.md
doc/orgmode.txt

Fix a typo

---

DOCS.md
ftplugin/org.vim
lua/orgmode/config/defaults.lua
lua/orgmode/config/init.lua

This PR permits configuration of the default fold level via the setup variable `org_startup_folded`.
- This PR fixes the issues identified in #614 as a user can now better modify the fold level used by Orgmode
- This PR also solves issues with `nvim-ufo` integration (#599) to a certain degree
- It "solves" the issue for `nvim-ufo` users (such as I) by permitting them to inherit their `vim.opt.foldlevel` instead of using Orgmode's provided fold level. This makes Orgmode play nice with `nvim-ufo`. My earlier problems with `fillchars` cannot be reproduced at this time, so I consider it a non-issue.
- Wrote documentation to the `DOCS.md` file for the new option. As a note I have ***not*** written new documentation to the Orgmode help file. I noticed that it appeared autogenerated so I held …

feat: Allow for configuration of `foldlevel` similar to Emacs Orgmode

---

DOCS.md

Changing this setting's description to what it actually corresponds to.

docs(folds): better org_startup_folded.showeverything description

---

lua/orgmode/objects/url.lua
lua/orgmode/utils/fs.lua
tests/plenary/object/url_spec.lua

Following a relative link starting with "../" is now supported.
Examples:
file:../somedir/some.org
../somedir/some.org
Previous it was possible to follow the first link, but a file "false" got opened instead of the target file. The second type was unsupported.
Because autocompletion works, it was easy for the user to create such links and surprising, that they didn't work.

fix(hyperlinks): link-follow for "file:../" and "../"

---

lua/orgmode/state/state.lua
lua/orgmode/utils/init.lua
tests/minimal_init.lua
tests/plenary/state/state_spec.lua

This is useful for features such as `org-clock-in-last` that has the ability to persist its "knowledge" of the last clocked in task. Org mode does this by saving to a cache file on system. This commit gives `nvim-orgmode` the same capability.
I'm creating this PR in what I consider a partially finished state. I'm primarily looking for feedback as to the design of this module. In the scenario we're all happy with the design then I can get some simple tests written and then promote this to a non draft PR.
Some quick notes:
1. This state management system uses the in-built promises library that `nvim-orgmode` bundles. This means there's some additional validation and steps taken than what might exist in fully synchronous code. 
2. I use a metatable to ensure any accesses against the `State` …

feat: add a way to cache state between restarts of Neovim

---

lua/orgmode/org/mappings.lua

Remove the need to save the file before following internal links to headlines in the same file.
This issue bugged me for quite some time and was actually an easy fix.

fix: follow internal links flawlessly

---

lua/orgmode/org/indent.lua

This is a really weird bug. I know it's an issue with how the `get_matches` function works and buftick. `indentexpr` isn't really intended for indenting many lines that all depend on each other's indents.
What this does is "freeze" the matches during a indent operation against a range of lines and only updates the previous matches' indent as necessary. By doing this we get "memory" for the indentexpr of the previous indents as part of a ranged indent operation like `norm! 0gg=G` which avoids any race conditions as to the speed of indents. Without this caching the `get_matches` function is called on every indentexpr operation, so for every line in the range, which can result in bad data back for calculating the indents.
I have added a big ol' comment above the indentexpr with further …

fix: cache indent matches to avoid occasional race conditions

---

lua/orgmode/capture/init.lua

This fixes #644. @kristijanhusak Could you please merge #641 first, because this PR builds upon it. I will then rebase this one. If you decide to merge this directly, we can close #641.

Fix refiling to current buffer (#644)

---

tests/plenary/state/state_spec.lua

Fix test on CLI AND Neotest by executing the vim commands asynchronously.
This test was not marked as failed when it ran from the command line, although the error was visible in the output.
In Neotest it was actually marked as failed.

fix: schedule vim commands in state_spec test

---

DOCS.md
ftplugin/org.lua
lua/orgmode/org/indent.lua
lua/orgmode/ui/virtual_indent.lua
lua/orgmode/utils/dict_watcher.lua
plugin/orgmode.vim
tests/plenary/org/indent_spec.lua

Following on from #627, this adds the capability to toggle virtual indentation within an orgmode buffer. This allows me to check one thing off my list [here](https://github.com/nvim-orgmode/orgmode/issues/422#issuecomment-1910991160).
See the short gif below:
Bullet list of changes:
- Refactored `VirtualIndent` to allow multiple instances to easily track attachment to different buffers
- Added capability to `VirtualIndent` to enable/disable based on `vim.b.org_indent_mode` using a timer set to check the variable every 50ms
- Added tests for new functionality
- Updated docs to reflect this new functionality (`org_startup_indented` is where I placed them)
Do I need to add a user command like `OrgToggleIndentMode` or a keybind for this? Or is using the buffer variable, …

feat: make VirtualIndent dynamically attach/detach based on `vim.b.org_indent_mode`

---

lua/orgmode/ui/virtual_indent.lua

Copied from the body of my commit message:
> On the current version of nightly (at the time of writing this is NVIM
v0.10.0-dev-2361+ga376d979b) the synchronous call doesn't seem to have
any value.
>
> Using only a scheduled call is seemingly smooth now -- perhaps when I
made the original commit I had something wrong with my configuration or
perhaps upstream Neovim fixed whatever was causing some choppiness?
>
> Another note is that `on_lines` in `nvim_buf_attach` can have `textlock`
restrictions and more applied, thus we really should just use
`vim.schedule` only anyhow.
*I* don't see any laggy behavior during promotions/demotions or undos on my side with the change in this PR, hence why I made it. 
It wouldn't hurt if someone else could check on their side with the latest nightly and …

refactor: remove sync call to set indent for virtual indents

---

DOCS.md
lua/orgmode/colors/highlighter/stars.lua
lua/orgmode/colors/highlights.lua
lua/orgmode/config/defaults.lua

Follow on from #627.
Bullet points:
- Added new config flag: `org_indent_mode_turns_on_hiding_stars` which is enabled by default
- Added docs reflecting new configuration flag
Crosses another one off [my list](https://github.com/nvim-orgmode/orgmode/issues/422#issuecomment-1910991160) of indent mode features.

feat: add `org-indent-mode-turns-on-hiding-stars` equivalent

---

lua/orgmode/init.lua

Copied from the commit message:
> This ensures that notifications do not error on startup. Prior to this commit the `OrgFiles` object wasn't loaded in time for notifications to work.
Currently Orgmode throws an error on startup on the `nightly` branch when notifications are enabled because the `Org` instance isn't ready in time for when the notifications are actually initialized. 
This was the simplest way I saw to ensure the notifications have `files` available on the `Org` instance at startup. 
Perhaps it would be better to move the notifications setup into the `Org:init` function and make the `config` object available across that module after setup? I didn't undertake that move as I'm not 100% sure as to the nuances involved with setting up the notifications and why they're setup …

fix: run Org init as part of setup

---

lua/orgmode/config/init.lua
lua/orgmode/files/elements/logbook.lua
lua/orgmode/files/elements/table/init.lua
lua/orgmode/files/headline.lua
lua/orgmode/org/indent.lua
lua/orgmode/org/mappings.lua

Always check for `vim.b.org_indent_mode` before applying indentation to the buffer.
If it's `true`, treat all indentations in a buffer as if the configuration has `org_startup_indented` enabled.
@PriceHiller can you review and test this to see if it works ok?

feat(indent): Always check for b:org_indent_mode if available

---

ftplugin/org.lua
lua/orgmode/colors/highlighter/foldtext.lua
lua/orgmode/colors/highlighter/init.lua
lua/orgmode/org/indent.lua
lua/orgmode/org/mappings.lua
lua/orgmode/utils/init.lua

Use new empty foldtext option (`set foldtext=`) to highlight folded lines. Also add `org_ellipsis` accordingly to look like Emacs Orgmode. Closes https://github.com/nvim-orgmode/orgmode/issues/661

feat(foldtext)!: Use new empty foldtext option for Neovim 0.10

---

queries/org/highlights.scm

This allows org tables to be highlighted similar to Markdown tables by treesitter.
See the screenshot below for a org table with the highlight groups:
See `:h treesitter-highlight` for the captures available. The captures used in this PR apply to nightly versions of Neovim which has changed the captures to be more in line with other editors.
Specifically, the captures used are:
- `@punctuation.special`
- `@markup.heading`

feat: add queries to highlight tables similar to markdown

---

lua/orgmode/org/mappings.lua

This enables opening URLs with `<leader>oo` even when netrw is not loaded.
Neovim `gx` was changed to this as well in 0.10.0 according to news.txt.
As far as I can tell, it was introduced here: https://github.com/neovim/neovim/pull/23401
I'm not sure if there's a better way to detect if `vim.ui.open` exists.
I'm also not sure if the return value is used for anything, but everything seemed to work fine.

fix: open external urls with vim.ui.open() if it exists

---

lua/orgmode/org/mappings.lua

Copied from the commit message:
> Since https://github.com/neovim/neovim/commit/2e1f5055acdef650c27efc4afdf8606037ec021b, Neovim now explicitly requires the bufnr for `vim.lsp.util.apply_text_edits` to be fully resolved — meaning it cannot be 0 or null.
This just ensures nightly users don't run into errors when using `meta return` and that the tests for nightly pass as expected.

fix(mappings): use explicit bufnr for meta return in `apply_text_edits`

---

lua/orgmode/org/indent.lua
lua/orgmode/ui/virtual_indent.lua

This PR addresses few indent issues:
1. Prevent "missing parent" errors when opening `#+begin` blocks outside of headline and list item
For example, having this content:
```
#+begin_src lua
print('test')
#+end_src
```
Pressing Enter on 2nd line currently errors out. 
2. If tree-sitter parsing is failing at the moment of requesting indentation, fallback to `-1` (autoindent). 
For example, having this content:
```
* TODO Test
#+begin_src lua
```
Pressing Enter on 2nd line to add a closing `#+end_src` will set indentation for that line to 0. This fallback ensures that indentation from previous line is followed.
3. For virtual indentation, if tree-sitter parsing is failing, fallback to searching closest headline by iterating previous lines. This removes some of the annoying jumps:
Before: …

fix(indents): Address few indent issues

---

lua/orgmode/clock/init.lua
lua/orgmode/init.lua

Hello,
With the last updates I've noticed that the `get_statusline()` function was slowing down my Neovim instance a lot and I think the problem is related with the way the clock gets the currently clocked in headline, which is basically parsing all files and retrieving the first clocked in headline.
Now, on my PC the slow down was barely noticeable, but on my Android phone it became a real issue (despite it being a good smartphone) so I did my best trying to patch it.
The basic idea is that now, with the modifications here, we pay a little upfront cost (it is noticeable on my phone but it is only at startup, I could not test it on my PC yet, will do later this week) but afterwards we store the information of the clocked headline in the instance of the clock itself, making it faster to …

Faster statusline

---

lua/orgmode/config/init.lua

Hello,
with the last refactoring I noticed that most languages were not being injected properly, I think that this is caused by the new directive `org-set-block-language!` which was returning `nil` for basically all the languages which were not listed in the map.
This should fix it.
I tested with the languages I use the most: `terraform`, `haskell`, `purescript` and `c_sharp` and it works well, it also works with the aliases from the map: `js`, `md`, ...
Since I am not that good when it comes to treesitter, there may be something else I'm missing, let me know!

fix(treesitter): correctly inject the language in blocks

---

lua/orgmode/colors/highlights.lua

This PR allows the linked highlights to not override/respect already set highlights.
This ensures any colorschemes or custom highlights set *before* Orgmode is loaded do not have their highlights invalidated when Orgmode loads or is reloaded. By setting `default = true` for the linked highlights, lazy loading plays nicer with Orgmode.

fix(highlights): make linked hls set `hi-default`

---

lua/orgmode/ui/virtual_indent.lua

Copied from the body of the commit:
> Prior to this commit, it was possible that virtual indents would only apply to the first heading in a range of lines and the other headings would lose virtual indentation.
> 
> This change makes the Treesitter lookup prefer the largest range of lines to set virtual indentation on and thus ensures virtual indent is set correctly across the entire range.
I noticed an issue when after saving a file with many headers in it, the virtual indent would only apply to the first header region and exclude the rest leaving the buffer with very wonky virtual indentation. This fixes that.
Note that this does not invalidate the need for the Treesitter lookup, as it is possible the Treesitter lookup specifies a larger range than the given lines. For instance, when …

fix(virtual indent): make TS lookup not exclude lines

---

lua/orgmode/org/indent.lua
tests/plenary/org/indent_spec.lua

This PR has two commits as part of it.
The first commit ensures when block contents have a single line at the correct indentation level and the rest of the contents are indented more than that line, the block contents won't have their indentation changed.
The second commit makes the block content indentation ignore blank lines. Meaning it won't modify indentation if a blank line is "underindented" relative to the header as it was previously.
I wrote tests as part of each commit to exercise each path. Please see them to see specific examples. Each commit has its own tests associated, so it may be easier to view them that way.
Let me know if there's anything else I can do :).

fix: block content alignment

---

lua/orgmode/ui/virtual_indent.lua

Copied from the body of the commit message:
> This ensures when the treesitter parser has errors, the manual indent
sizing doesn't return virtual indentation for headlines.
What's annoying is that the tests didn't catch this -- need a test to check raw insertion and typing I guess. That would've caught this for sure. The current tests loads the file, where the virtual indent works as expected.
Something to put on my TODO when I have more time.
Again, if anything crops up with Virtual Indent, ping me. I'll gladly look at it.

fix(virtual indent): do not return virtual indentation for headlines

---

lua/orgmode/utils/promise.lua
tests/plenary/utils/promise_spec.lua

Per the comment I made in our main org roam issue, I discovered that `Promise.wait` does not throw an error when the timeout is reached. Instead, it returns `nil`.
This can be a problem if you're returning `OrgPromise<nil>`, as it misleads the promise as succeeding when in reality it may have not completed yet.
This updates `Promise.wait` to check the return values from `vim.wait` to determine if a value should be returned or if an error should be thrown.

Update promise.wait to throw an error when timeout reached or interrupted

---

doc/orgmode.txt

According to [this file](https://github.com/nvim-orgmode/orgmode/blob/8ec0bcc6f6476d246159f738081256c97a7a9b2c/lua/orgmode/colors/highlighter/stars.lua#L36), highlight for leading stars should be `@org.leading_stars` instead of `@org.leading.stars`.

update doc to use correct highlight name

---

DOCS.md
lua/orgmode/config/defaults.lua
lua/orgmode/config/mappings/init.lua
lua/orgmode/org/mappings.lua

Allows to make active timestamp inactive and vice versa with one keybinding.
Implements feature request #652.
It is part of Emacs Orgmode, but not mapped.
See also:
- https://doc.endlessparentheses.com/Fun/org-toggle-timestamp-type.html
- https://emacs.stackexchange.com/questions/38062/configure-key-to-toggle-between-active-and-inactive-timestamps/38064#38064

feature: support org_toggle_timestamp_type

---

lua/orgmode/api/init.lua
lua/orgmode/org/hyperlinks/init.lua
lua/orgmode/org/mappings.lua

To give plugins like Telescope-orgmode the ability to insert links, the API needs an extension.
The refactoring moves some methods from org.mappings into modules, where they should belong anyway, so they can be used from the new api method.
The new API method api.insert_link is mostly existing code moved from org.mappings.insert_link, which now just calls api.insert_link.

feat(api): Allow to insert links through API

---

tests/plenary/ui/mappings/archive_spec.lua

Given
```
* foo
** bar
*** baz
```
and the cursor on the foo-line, when archiving, the archive context is added to the last headline:
```
* foo
** bar
*** baz
:PROPERTIES:
:ARCHIVE_TIME: ...
...
:END:
```
Emacs however adds the archive context to the foo-headline (which seems to be more appropriate):
```
* foo
:PROPERTIES:
:ARCHIVE_TIME: ...
...
:END:
** bar
*** baz
```
Hence this PR, which aligns nvim-orgmode's behaviour with Emacs.
BTW, I second @seflue 's suggestion from https://github.com/nvim-orgmode/orgmode/pull/641#issue-2061135549 and https://github.com/nvim-orgmode/orgmode/issues/645#issuecomment-1881724227 to extract Refile and Archive from Capture (probably analogous to, `org-capture.el`, `org-refile.el`, and `org-archive.el` in …

Add tests for archiving subtree

---

lua/orgmode/objects/date.lua

Store all attributes passed as option via Date:set, especially date_only.
I am raising this as a separate PR and precondition to PR #650. If we don't treat every field in the given date consequently, we get suprising behavior if some of the fields are present within the given "time" parameter. The idea of the function is, to allow adjusting an existing date instance by a subset of it's fields given as a table and returns the adjusted date as new value from the method.
This fix ensures, that every field can actually be adjusted within this function. I observed bugs while working on my time picker, if I used this function to get a Date object with adjusted time values (hours, minutes).

fix(date): persist all attributes passed by options

---

README.org

This entire plugin is about orgmode. I recently noticed that github supports formatting README files with `.org` notation.
I let myself be inspired by [this beautiful repo](https://github.com/emacs-tw/awesome-emacs/tree/master) and decided I'd try my hand at migrating this repos' README as it only felt fitting.
I had to make two concessions to read feature parity with your readme:
1. `<kbd>` tags and inline code look the same
- I did format kbd tags with `=key=` notation and inline code with `~code~` notation to make it easier to refactor if a better solution is found
2. Checkmarks (`- [ ]` and `- [x]`) were not getting formatted properly
- I used emojis with `:white_check_mark:` and `:white_square_button:` to obtain a similar effect
Feel free to look at the result on [my fork of the …

Migrate from README.md to README.org

---

lua/orgmode/org/hyperlinks/init.lua

When inserting a stored id link, it is now properly split into link and description.
For this to work with the current implementation we need actually to insert id and headline title both into the link input. It get's split and correctly formatted afterwards.

fix(links): insert id link properly

---

lua/orgmode/objects/date.lua

- introduce types for internal date tables
- introduce some helper to encapsulate interaction with os api

refactor(date): improve type hints

---

lua/orgmode/org/mappings.lua
tests/plenary/ui/mappings/headline_spec.lua

Allows to move subtrees around smoothly (e.g. using [Hydra.nvim](https://github.com/anuvyklack/hydra.nvim), see #752). It also fixes the foldings after changing the subtree and preserves the folding state in the current subtree when moving it up or down.

Fix subtree move (fixes #752)

---

lua/orgmode/objects/edit_special/types/src.lua

There exists the same issue as in https://github.com/nvim-orgmode/orgmode/issues/727 for `org edit special`.
This commit uses the same logic as the one to handle the case in highlight injection to solve the problem for `edit-special`.

fix: fix file type detection in `org-edit-special` on macOS.

---

lua/orgmode/org/hyperlinks/init.lua
lua/orgmode/org/hyperlinks/url.lua
lua/orgmode/utils/fs.lua
tests/plenary/helpers.lua
tests/plenary/org/autocompletion_spec.lua

Hi guys, I am trying to hack for ~/ prefixs. 
Even if the cmp is configured with org-mode and path sources, the `<space>oli` cannot auto-complete the `~/` prefix. 
Also, this issue is the same at emacs org-mode. 
It is useful as I have multiple machines to sync with. I set my org folder as `~/org/`, but the `~` can be 
1. private macOS: `/User/pf/`
2. Working Linux: `/home/pf/`
3. ...
Any suggestion is appreciated. :)

feat(core): enhance org-insert-link, add completion for `~/`  prefix.

---

lua/orgmode/org/mappings.lua
tests/plenary/ui/mappings/headline_spec.lua

Previously, `next-visible-heading`, moved to the next heading, regardless of its visibility.

bug(core) Ignore invisible headings

---

lua/orgmode/config/init.lua
queries/org/highlights.scm

rather than define queries for set n=8 depth headlines, set autocommand that searches for stars and uses length of stars text to determine depth using modulo operation to wrap for number of color groups (hardcoded still at 8, but would be nice to define any number of groups easily in the futur

Add dynamic query for coloring n-depth headlines

---

README.org
lua/orgmode/init.lua

Hello, this branch contains two commits:
1) the first one fixes the links on the top of the README.org file, creating custom_ids for all the needed headlines and using the `file:` notation for other files in the repository, thus making it easier to navigate the file while in Neovim;
2) the second one increments the timeout of the promise for the `load_sync` method of `OrgFiles` to 15 seconds. I know it might sound a lot, but on very slow devices (for example my Android phone, where I use orgmode and [org-roam](https://github.com/chipsenkbeil/org-roam.nvim) a lot) loading my > 100 files takes slightly more than 5 seconds, and sometimes it fails and I am therefore forced to `:Lazy reload` over and over again, until the caching of the OS is good and it loads in less than 5 seconds. I thought …

Links for README.org + increase timeout for load_sync

---

README.org

With the trailing `)` it ends up going to the issue search section instead, looking for whoever username `49` may be :)

docs: fix readme links to notification issue

---

DOCS.md
lua/orgmode/config/mappings/map_entry.lua
tests/plenary/config/config_spec.lua
tests/plenary/init_spec.lua

Allows the optional configuration of a keymap's `desc` alongside its `lhs`.
Related issues:
https://github.com/nvim-orgmode/orgmode/issues/788
https://github.com/nvim-orgmode/orgmode/issues/781

feat: allow configuring keymap descriptions

---

lua/orgmode/colors/highlighter/stars.lua
lua/orgmode/ui/virtual_indent.lua
lua/orgmode/utils/treesitter/init.lua

Fixes chipsenkbeil/org-roam.nvim#49
Org-roam offers a "node buffer", a sidebar that shows information such as backlinks from other locations to the current headline/file. The node buffer allows previewing the location of such a backlink. This inserts orgmode syntax into a buffer with filetype `org-roam-node-buffer`.
If virtual indent is enabled, it'll attempt to deduce the virtual indent of the preview. This in turn calls `closest_headline_node()`, which in turn calls `get_node_at_cursor`, which in turn calls `vim.treesitter.get_node()`.
If `get_node()` is called without an explicit treesitter language, it'll attempt to deduce that language from the filetype. The filetype `org-roam-node-buffer` isn't associated with the `org` language (and I don't think it *should*), so this call fails. …

fix: explicitly pass treesitter language to `get_node()`

---

lua/orgmode/api/file.lua
lua/orgmode/api/headline.lua
lua/orgmode/api/init.lua
lua/orgmode/files/file.lua
lua/orgmode/org/autocompletion/sources/hyperlinks.lua
lua/orgmode/org/links/types/headline_search.lua
lua/orgmode/org/links/utils.lua
lua/orgmode/org/mappings.lua
tests/plenary/ui/mappings/hyperlink_spec.lua

Start using new links structure introduced in https://github.com/nvim-orgmode/orgmode/pull/802.
@chipsenkbeil can you check if using this branch breaks anything in org-roam.nvim? It shouldn't, but it's best to double check.
You will need to introduce one change here: https://github.com/chipsenkbeil/org-roam.nvim/blob/192732a8de167e7770b12db31e737239311b1a43/lua/org-roam/setup/plugin.lua?plain=1#L20
I added a hyperlink class in https://github.com/nvim-orgmode/orgmode/blob/71c57cab31b78d2c6907d2961b6c2666ea9383a1/lua/orgmode/org/links/hyperlink.lua?plain=1#L8, and it works basically the same for your usage. Underlining `url` prop is also a different class, but it has the `get_id` method that you are using.
For this line you can use `Hyperlink.at_cursor` function instead of these 3 lines to …

feat(links)!: Use refactor links structure

---

lua/orgmode/agenda/views/tags.lua

`<leader>oa` + `m` - Match a TAGS/PROP/TODO query prompt autocomplete isn't working on `<tab>`.

fix: fix autocomplete for tags search prompt

---

lua/orgmode/capture/init.lua
lua/orgmode/files/headline.lua
tests/plenary/ui/mappings/archive_spec.lua

This adds the outline path (`ARCHIVE_OLPATH`, i.e. the list of ancestors of the archived headline) to the archive context. In Emacs, see
* org-archive-save-context-info: https://github.com/emacs-mirror/emacs/blob/7f415f7d5e19ea3903500426a0724e49271ac699/lisp/org/org-archive.el#L119
* org-get-outline-path: https://github.com/emacs-mirror/emacs/blob/7f415f7d5e19ea3903500426a0724e49271ac699/lisp/org/org.el#L7464
This PR includes a fix to set the `ARCHIVE_TODO` attribute as well.
I checked with Emacs first and then specified the test to match what Emacs does. Looking forward to any feedback you might have!

feat(archive): set outline path when archiving

---

lua/orgmode/capture/init.lua

Hi, I really like this project!
I'm using the org-roam plugin, and it will prefix every file with the current timestamp to make sure it's unique (e.g. `20241013095846-helloworld.org`).
Refiling to such files is really inconvenient as I need to circle through all filenames with the TAB key.
Searching for it is really cumbersome as I'd have to type in the exact timestamp of this orgfile.
My suggestion is to remove the anchor (`^`) from the file pattern matching, and allow the search string to be anywhere in the filename.
This way I can just type `hello` or even `world` to quickly select the refile target.

feat(refile): improve ux by matching files more fuzzily

---

lua/orgmode/org/indent.lua

Avoid errors when refiling content with headlines and enabled virtual indentation.
Cause: Indentation is also implicitly calculated during refiling. In this case the buffer could already be invalid.

fix(virtual indent): handle invalid buffer gracefully

---

lua/orgmode/capture/init.lua
lua/orgmode/utils/fs.lua

fix(refile): Autocomplete nested paths

---

lua/orgmode/org/mappings.lua
tests/plenary/ui/mappings/todo_spec.lua

In emacs orgmode, the `org-log-note-headings` is defined as follows:
```lisp
(defcustom org-log-note-headings
'((done .  "CLOSING NOTE %t")
(state . "State %-12s from %-12S %t")
(note .  "Note taken on %t")
(reschedule .  "Rescheduled from %S on %t")
(delschedule .  "Not scheduled, was %S on %t")
(redeadline .  "New deadline from %S on %t")
(deldeadline .  "Removed deadline, was %S on %t")
(refile . "Refiled on %t")
(clock-out . ""))
"Headings for notes added to entries.
```
This commit changes the log state format so that it is aligned with emacs orgmode.

feat(log-state): align with the emacs orgmode format

---

lua/orgmode/files/headline.lua

If a tag is excluded from inheritance, then it gets excluded even from headlines that have it assigned directly. This is most noticable when searching in agenda view. This PR fixes it - you can now search by tags that are excluded from inheritance.
Fixes #830

fix: retain direct tags even if they are excluded from inheritance

---

lua/orgmode/objects/help.lua

Hey :wave:
I have disabled a few keymaps in my config following [docs](https://github.com/nvim-orgmode/orgmode/blob/master/DOCS.md#mappings), and when I opened the help menu(`g?`), it was failing to open due to disabled keymaps.

fix(help): ignore disabled mappings

---

lua/orgmode/capture/template/init.lua

This fixes the order which the template is compiled. Previously, the expressions `%()` were compiled _before_ expandable variables (such as `%x`). This made the example template in [1] to produce:
```org
* [[url][x]]
```
instead of
```org
* [[url][end part of the url]]
```
By doing the expression compilation _after_ expandable ones, this issue is resolved.
[1] https://github.com/nvim-orgmode/orgmode/wiki/Getting-Started#captures

fix(template): expandable variables in lua expr

---

.github/workflows/docgen.yml
docs/configuration.org
lua/orgmode/agenda/init.lua
lua/orgmode/agenda/types/agenda.lua
lua/orgmode/agenda/types/init.lua
lua/orgmode/agenda/types/search.lua
lua/orgmode/agenda/types/tags.lua
lua/orgmode/agenda/types/todo.lua
lua/orgmode/api/init.lua
lua/orgmode/capture/init.lua
lua/orgmode/capture/template/init.lua
lua/orgmode/clock/init.lua
lua/orgmode/config/_meta.lua
lua/orgmode/config/defaults.lua
lua/orgmode/org/hyperlinks/init.lua
lua/orgmode/org/links/init.lua
lua/orgmode/org/mappings.lua
lua/orgmode/ui/input.lua
lua/orgmode/utils/init.lua
lua/orgmode/utils/promise.lua
tests/plenary/api/api_spec.lua
tests/plenary/capture/capture_spec.lua

feat(input): Add async input

---

lua/orgmode/utils/init.lua

Previously, when the viewer opened, the editor was blocked until the user closes the viewer. Now, the viewer opens asynchronously (using `vim.system` rather than the old `vim.fn.system`); in this way, the user can view the PDF while continuing editing the org file in the editor.

Run viewer asynchronously using `vim.system`

---

.github/pull_request_template.md
.github/workflows/release.yml
docs/contributing.org

This PR adds a GitHub actions workflow to automate the creation of semantically versioned releases with `release-please` and a PR template to encourage compliance with conventional commits.
Closes #828 
- Added `release-please` workflow
- Added PR template
- Updated Contributing documentation to mention conventional commits
`make test`.

ci, doc: add semver workflow and PR template

---

docs/configuration.org

This PR fix `org_todo_repeat_to_state` description and remove redundant `***` heading lines above `org_archive_location`
Related #
Closes #
- fix `org_todo_repeat_to_state` description
- remove redundant `***` heading lines above `org_archive_location`
`make test`.

chore(docs): fix `org_todo_repeat_to_state` description

---

docs/configuration.org
lua/orgmode/api/headline.lua
lua/orgmode/clock/init.lua
lua/orgmode/config/_meta.lua
lua/orgmode/config/defaults.lua
lua/orgmode/config/init.lua
lua/orgmode/files/file.lua
lua/orgmode/files/headline.lua
lua/orgmode/org/hyperlinks/init.lua
lua/orgmode/org/links/types/custom_id.lua
lua/orgmode/org/links/types/id.lua
lua/orgmode/ui/menu.lua
lua/orgmode/utils/init.lua
tests/plenary/files/headline_spec.lua

This PR adds the option `org_use_property_inheritance` and allows using [property inheritance](https://orgmode.org/manual/Property-Inheritance.html) in searches and via the external API.
The code to search for a property recursively was already there, it's just that the default behavior couldn't be configured.
I've changed the behavior of `get_property()`'s parameter `search_parents` from two-state (truthy=yes, falsy=no) to tri-state (`true`=yes, `false`=no, `nil`=use config).
For the config itself, I've added the option itself and also a method `OrgConfig:use_property_inheritance()`, which evaluates it for a given property name.
I've adjusted the special cases where we want to always ignore (or always use) inheritance by grepping the code base for `get_property` and …

feat(properties): add option `org_use_property_inheritance`

---

lua/orgmode/events/init.lua

Minor clean-up of `EventManager` by using `vim.defaulttable` instead of custom logic.
- fix a minor type issue in `EventManager.init`
- replace custom logic in `EventManager.listen` with `vim.defaulttable`

refactor(events): use `vim.defaulttable` in `EventManager`

---

lua/orgmode/capture/init.lua
lua/orgmode/files/file.lua
lua/orgmode/files/init.lua
lua/orgmode/notifications/init.lua
lua/orgmode/utils/fs.lua
lua/orgmode/utils/init.lua
lua/orgmode/utils/treesitter/install.lua
scripts/minimal_init.lua
tests/minimal_init.lua
tests/plenary/babel/tangle_spec.lua
tests/plenary/files/file_spec.lua
tests/plenary/state/state_spec.lua

Replace `vim.loop` with `vim.uv`. The former has been [deprecated ][1] since 0.10, which is our minimum version, as far as I can tell.
[1]: https://neovim.io/doc/user/deprecated.html#vim.loop
None
- replaced `vim.loop` with `vim.uv` in manual search & replace
- `scripts/minimal_init.lua` also had its quotes changed by Stylua
- Running `Stylua` inside `scripts/` produced *a lot* of changes; I left those in other files out to avoid cluttering the diff.
- There are two files[^2] with lines `local uv = vim.loop` at the top, that now read `local uv = vim.uv`. I'm not sure about the purpose of these (in Python, you'd do this to avoid repeated attribute lookups, which can be costly), so I left them as is.
- where those files still used `vim.loop`, I replaced it with `uv`, not `vim.uv` for …

refactor: replace deprecated vim.loop with vim.uv

---

lua/orgmode/org/mappings.lua
tests/plenary/helpers.lua
tests/plenary/utils/fs_spec.lua
tests/plenary/utils_spec.lua

These are some tests I wrote while wrapping my head around how the path-handling utils work. :slightly_smiling_face: 
I've split things into multiple commits to make the review a bit easier.
- changed one function in `mappings.lua` from formatting headline tags manually to using `utils.tags_to_string()`
- changed one occurrence of `vim.cmd(("edit %s"):format(file))` to `vim.cmd.edit(file)`
- refactored `tests/plenary/helpers.lua` to declare its exported functions the same way all other modules do
- added functions `with_var()` and `with_cwd()` to `helpers.lua` to temporarily change global state
- added tests for `utils.current_file_path()` function
- added tests for `utils.fs` module

feat(tests): add tests for `utils.fs` and `utils.current_file_path()`

---

lua/orgmode/export/init.lua
lua/orgmode/utils/init.lua

This PR removes the function [`utils.open()`][1] and replaces it with [`vim.ui.open()`][2].
[1]: https://github.com/nvim-orgmode/orgmode/blob/3583faceee01ef684645476a1feb07ab3688f6d1/lua/orgmode/utils/init.lua#L97-L112
[2]: https://github.com/neovim/neovim/blob/e4a58a7ca03457668492f8f41189ea2f23700172/runtime/lua/vim/ui.lua#L136-L172
As far as I can tell, this helper was only used in `export.lua`. Hyperlinks used `vim.ui.open()` from the start.
The utils function does basically the same as the built-in, except:
1. doesn't return an awaitable object
2. doesn't search for executables as thoroughly.
- replaced `utils.open()` in export.lua with `vim.ui.open()`
- removed the function itself

refactor(utils): replace utils.open() with vim.open()

---

docs/configuration.org
lua/orgmode/config/_meta.lua
lua/orgmode/config/defaults.lua
lua/orgmode/org/links/init.lua

Add support for setting up custom hyperlink types.
Closes #783 and #387 
`make test`.

feat(hyperlinks): add ability to add custom hyperlink sources

---

lua/orgmode/utils/init.lua
tests/plenary/org/fold_spec.lua
tests/plenary/utils_spec.lua

This PR adds an optional flag to `utils.writefile()` to enable exclusive writes. Such a write fails if a file with the given name already exists.
The org-attach feature requires functionality like this because it is really adamant about not overwriting attachments that the user might not be aware of. [Example here](https://github.com/emacs-mirror/emacs/blob/4da38c632161867e914b3a13dc760f8019255f94/lisp/org/org-attach.el#L559-L560).
Slowly getting there …
- Add new optional parameter `opts` to `utils.writefile()`. Right now, the only option is a boolean flag `excl`.
- Add tests for `utils.writefile()`
- Add tests for `utils.readfile()`
- Also add a tiny test for folds; I was debugging an issue with folding earlier (turns out lazy loading was the culprit) and since …

feat(utils): add optional flag to `utils.writefile()` for exclusive writes

---

docs/plugins.org

Rolodex is changing its name to RLDX to avoid any down-the-road trademark issues. Updating those changes here too.

Name Change: rolodex.nvim -> RLDX.nvim

---

lua/orgmode/ui/input.lua

Allow `ui.input` to take not only functions for custom completion, but also strings for buil-in completion.
The org-attach feature uses both the `dir` built-in completion (to choose a directory to attach) and the `buffer` built-in completion (to choose a buffer whose contents are to be attached).
Extracted from #878
- adjust type signature of `orgmode.ui.input.open()` to allow string-type completion arguments
- special-case on `type(completion)` being a string.

fix(ui): allow built-in completions in orgmode.ui.input

---

.github/workflows/tests.yml
lua/orgmode/files/init.lua
tests/plenary/utils_spec.lua

Fix checkbox issues with nightly.
Closes #813
- Updated toggle checkbox to work with nighly
`make test`.

fix(nightly): fix checkbox issues with nightly

---

queries/org/highlights.scm

Ensures a org table only has its heading get the `@org.table.heading` highlight/group applied.
Prior to this, it seems the relevant highlight query accidentally applied to the body of tables as well.
_Before this change:_
_After this change:_
- Updates the TS query for table heading highlights to restrict them to _only_ the first heading
`make test`.

fix(ts): correctly highlight table headings

---

lua/orgmode/agenda/types/agenda.lua

This PR adds.. Core feature parity with emacs agenda views. All view changes should take into account the cursor position.
Currently, view month and view day both shift the cursor to and start the view's span from the start day (Monday by default). In emacs, all view changes take into account the agenda date that the cursor is on, and then choose the start date accordingly. These changes aim to mimic emacs behavior by
1. modifying all view changes to stop moving the cursor
2. displaying the week number in all spans types
3. change the first day of the view to be the first day of the span
1. modifying all view changes to stop moving the cursor
2. displaying the week number in all spans types
3. change the first day of the view to be the first day of the span
To expand on 3, month view …

fix(agenda): make spans work like emacs

---

lua/orgmode/babel/tangle.lua

When tangling code blocks to files, automatically create parent directories when the :mkdirp header argument is set to 'yes'.
The ‘mkdirp’ header argument creates parent directories for tangled files if the directory does not exist. A ‘yes’ value enables directory creation whereas ‘no’ inhibits it.
https://github.com/nvim-orgmode/orgmode/issues/927

feat(babel): add directory creation support with :mkdirp header argument

---

lua/orgmode/files/elements/listitem.lua
lua/orgmode/files/headline.lua
tests/plenary/ui/mappings/checkbox_spec.lua

On master if a headline has multiple lists, the cookie is only updated for the current list. In emacs org, the cookie reflects information about all lists under the headline. This PR just makes it so. 
On master the headline would show either 2/3 or 1/1 depending where the last update happens. 
`make test`.

feat: support updating a headline's cookie from multiple lists

---

lua/orgmode/capture/template/init.lua

When creating capturing templates we can un the `%n` variable to insert the current user. It is done by using the environment variable `USER`. However, in Windows the variable is called `USERNAME`. This PR fixes this issue.
This PR adds..
Related #
Closes #
- Check whether it is being run in Windows.
- If is running in Windows it uses the environment variable `USERNAME` to query the current user name, otherwise it uses the `USER` variable.
`make test`.

fix(template): Use env variable USERNAME in Windows

---

lua/orgmode/files/headline.lua
tests/plenary/ui/mappings/todo_spec.lua

Add function `update_todo_cookie` to update a headline's cookie from a TODO state change.
Closes #305
`make test`.

feat: support  headline's cookie from TODOs

---

lua/orgmode/files/headline.lua
tests/plenary/ui/mappings/todo_spec.lua

@kristijanhusak Sorry to open this again, I made a mistake when creating the original PR from Octo.nvim: The base branch selected was the master branch from my forked repository, not the original upstream repository. So the PR merge went into the wrong branch.
Previously, the todo statistics cookie was counting all child headlines in its calculation, regardless of whether they had TODO keywords. This fix modifies the `update_todo_cookie` function to:
1. Filter child headlines to only those with valid TODO keywords
2. Calculate the ratio of DONE tasks to total tasks with TODO keywords
3. Update the cookie with the correct statistics
This ensures consistency with Org Mode's behavior where non-task headlines are excluded from statistics calculations.
This PR adds..
Related #
Closes #
- List …

fix(statistics cookie): count only TODO headlines

---

queries/org/images.scm

This PR adds support for rendering LaTeX math expressions in org files by using snacks.images.
Related: #907
- Add a tree-sitter query for detecting latex math expressions
`make test`.

feat(images): add support for rendering latex math expressions

---

queries/org/images.scm

Add latex preview image for common markups/blocks
Related PRs
- #935 
- #907 
- Let the rendering match `latex` source 
- Let the rendering match `equation` block
- Let the rendering match `\[\]` block (`latex_env` in Org Treesitter)
`make test`.
For typst, the rendering is feasible and only just feasible, I did not commit that change, the snippet is below
```scheme
; NOTE: This is buggy
(block
name: (expr) @name
parameter: (expr) @lang
contents: (contents) @image.content 
(#match? @name "(src|SRC)")
(#match? @lang "(typst|TYPST)")
(#set! injection.language "typst")
(#set! image.ext "math.typ"))
```
Maybe …

feat(image): match latex code tag for math preview

---

lua/orgmode/org/mappings.lua

Move insert_item logic out of meta_return into a reusable function. In a follow up, https://github.com/nvim-orgmode/orgmode/pull/943 will make meta_return logic even cleaner. This will make it easy for one to customize meta_return's behavior in their config. 
- As title.
`make test`.

refactor:  move insert_item logic out of meta_return

---

lua/orgmode/org/mappings.lua
lua/orgmode/utils/treesitter/init.lua
tests/plenary/ui/mappings/meta_return_spec.lua

Meta return doesn't work when the cursor is on a link because currently we don't handle link in the logic to find a headline or listitem node (the added test would be failing on master).
This PR factor out that logic into a reusable `find_item_or_headline` function and make it a bit more general. 
`make test`.

fix: meta_return on a link item

---

.github/workflows/tests.yml
lua/orgmode/files/init.lua

Remove deprecation warnings with nvim 0.11.

chore: remove usage of deprecated neovim functions

---

lua/orgmode/org/global.lua

Handles no arguments being used with `:Org` with standard echo error.
Related #
Closes #
- List changes here
{depends on definition of thorough)
`make test`.

fix: handle empty :Org arguments.

---

lua/orgmode/files/file.lua

Emacs org-mode allows for matching based on a variable LEVEL which represents the level of the headline. This change enables this feature.
See https://orgmode.org/manual/Matching-tags-and-properties.html
Related #
Closes #
- Adds LEVEL variable to predicate searches
`make test`.

feat: add ability to search on LEVEL

---

queries/org/images.scm

This PR adds `svg` to the list of supported image types. It seems that this was missed during the first implementation.
- Related https://github.com/folke/snacks.nvim/issues/1276 
- Related https://github.com/nvim-orgmode/orgmode/pull/907
Closes #
- Simply added `svg` to the list in `queries/org/images.scm`.
`make test`.

fix(images): add svg to list of supported image types

---

docs/configuration.org
docs/index.org

Fixes a few minor typos in `/docs`
- Spelling fix in index.org (youf -> your)
- Spacing fix in configuration.org
- Spelling fix in configuration.org (withing -> within)
- Fix data type in configuration.org (extraneous `<`)
`make test`.

docs: fix minor typos

---

lua/orgmode/org/indent.lua
tests/plenary/org/indent_spec.lua

At the end of a `listitem`, if we hit Enter in insert mode, the cursor will be indented in the following line; if we hit o to enter the new line from normal mode, the cursor will not be indented. The added test is failing on master. This PR fixes that.
Closes #940
`make test`.

fix: indent an item's content when entering a new line from normal mode

---

lua/orgmode/health.lua
lua/orgmode/utils/treesitter/install.lua

Allow tree-sitter grammar for Org to be installed outside of orgmode installation directory, either via nix or luarocks.
Related #967
- Allow parser to be installed outside of the orgmode installation directory
- Report conflicting parsers only if there is more than 1 installation found
- Track/report the version and attempt to update/reinstall only if parser is installed by nvim-orgmode in the orgmode installation directory.
- Compiled parser is now moved via CLI `mv` command (or Windows `move` cmd) instead of `fs_copyfile`. `fs_copyfile` caused Neovim to crash when updating/reinstalling. This is also how nvim-treesitter does it.
`docs: …

fix(treesitter): Allow tree-sitter grammar installation outside of orgmode folder

---

queries/org/highlights.scm

Back when hyperlinks still used extmarks, we disabled spell-checking for the URL part (d383f5c514c1ac10ae2f76c4d427c702fa1e5d8e). This must've gotten lost when switching over to treesitter queries.
This PR disables spell-checking again in `highlights.scm`.
Related to #547 
- Annotate the URL portion of the two relevant queries (`[[url]]` and `[[url][description]]`) with `@nospell`.
`make test`.

fix: disable spell-check in URLs

---

docs/configuration.org
docs/plugins.org

Thanks for always maintaining `nvim-orgmode/orgmode`!
I started using orgmode with this plugin, and it makes my task management easier!
Thank you so much!
This PR fixes the absences of line break in the document website.
https://nvim-orgmode.github.io/configuration#org_use_tag_inheritance
https://nvim-orgmode.github.io/plugins#nvim-cmp
N/A
- The absences of line break in the document website are fixed.
`make test`.

docs: fix absences of line break

---

docs/configuration.org
docs/index.org

36aa2f2 docs: fix lua code for combined agenda view config
bfbd30f docs: fix link to orgmode_api.txt
Currently the link to the txt file results in 404 on the docs:
https://nvim-orgmode.github.io/#api-docs
n/a
Just docs tweaks
`make test`.

docs: fix link to orgmode_api.txt

---

docs/configuration.org

This PR fixes a typo in the configuration docs linking to the date tree footnote in the official orgmode.org manual. 
Not applicable.
- `.hml` -> `.html` in the link to [https://orgmode.org/manual/Template-elements.html#FOOT84](https://orgmode.org/manual/Template-elements.html#FOOT84)
- [-] **Added tests** (if applicable) and verified existing tests pass with
`make test`.

docs: typo fix in config link to official documentation

---

.github/workflows/tests.yml
lua/orgmode/colors/highlighter/init.lua
lua/orgmode/colors/highlighter/markup/init.lua

Use treesitter async parsing for rendering markup. Should fix #1026

feat(treesitter)!: Use async parsing for custom highlighter

---

lua/orgmode/utils/fs.lua

There was a bug on Windows where the first character of the file name was dropped during refile. This happened because an extra leading / was added to the beginning of the path, resulting in something like: `/C:/org/file.org` which was then displayed as: `ile.org`.
Some issue was reported in https://github.com/nvim-orgmode/orgmode/issues/911, but not fixed on Windows.
Added OS check and fixed path construction
`make test`.

fix(windows): handle Windows file paths correctly in refile
